---
- name: Create .zshrc from example
  shell: |
    cd $HOME/.dotfiles
    cp .zshrc.example .zshrc
    cd -
- name: Create .config and .local
  shell: |
    cd 
    mkdir .config
    mkdir .local
    cd -
- name: Create ~/.tmux/plugins folder and link homebrew-installed tpm
  shell: |
    cd
    mkdir .tmux/plugins
    cd .tmux/plugins
    ln -s $(brew --prefix)/opt/tpm/share/tpm tpm
    cd -
