---
- name: Create .zshrc from example
  shell: |
    cd $HOME/.dotfiles
    cp -n .zshrc.example .zshrc
    cd -
- name: Create .config and .local/bin
  shell: |
    cd 
    mkdir -p .config
    mkdir -p .local/bin
    cd -
- name: Check if tpm is installed
  shell: "ls ~/.tmux/plugins 2>/dev/null | grep tpm || true"
  register: tpm_installed
- name: Create ~/.tmux/plugins folder and link homebrew-installed tpm
  shell: |
    cd
    mkdir -p .tmux/plugins
    cd .tmux/plugins
    ln -s $(brew --prefix)/opt/tpm/share/tpm tpm
    cd -
  when: tpm_installed.stdout == ""
